In [21]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score,confusion_matrix,accuracy_score,cohen_kappa_score
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.utils import resample

In [5]:
data = pd.read_csv(r"C:\Users\Silla Naresh\Desktop\caravan-insurance-challenge\caravan-insurance-challenge.csv")


In [6]:
data.shape

(9822, 87)

In [7]:
data[data["CARAVAN"]==1].iloc[:,0].count()/data.iloc[:,0].count()

0.059661983302789656

In [8]:
train =data.iloc[1:5822,:]
test = data.iloc[5823:,:]

In [9]:
x =['MOSTYPE','MAANTHUI',
 'MGEMOMV',
 'MGEMLEEF',
 'MOSHOOFD',
 'MGODRK',
 'MGODPR',
 'MGODOV',
 'MGODGE',
 'MRELGE',
 'MRELSA',
 'MRELOV',
 'MFALLEEN',
 'MFGEKIND',
 'MFWEKIND',
 'MOPLHOOG',
 'MOPLMIDD',
 'MOPLLAAG',
 'MBERHOOG',
 'MBERZELF',
 'MBERBOER',
 'MBERMIDD',
 'MBERARBG',
 'MBERARBO',
 'MSKA',
 'MSKB1',
 'MSKB2',
 'MSKC',
 'MSKD',
 'MHHUUR',
 'MHKOOP',
 'MAUT1',
 'MAUT2',
 'MAUT0',
 'MZFONDS',
 'MZPART',
 'MINKM30',
 'MINK3045',
 'MINK4575',
 'MINK7512',
 'MINK123M',
 'MINKGEM',
 'MKOOPKLA',
 'PWAPART',
 'PWABEDR',
 'PWALAND',
 'PPERSAUT',
 'PBESAUT',
 'PMOTSCO',
 'PVRAAUT',
 'PAANHANG',
 'PTRACTOR',
 'PWERKT',
 'PBROM',
 'PLEVEN',
 'PPERSONG',
 'PGEZONG',
 'PWAOREG',
 'PBRAND',
 'PZEILPL',
 'PPLEZIER',
 'PFIETS',
 'PINBOED',
 'PBYSTAND',
 'AWAPART',
 'AWABEDR',
 'AWALAND',
 'APERSAUT',
 'ABESAUT',
 'AMOTSCO',
 'AVRAAUT',
 'AAANHANG',
 'ATRACTOR',
 'AWERKT',
 'ABROM',
 'ALEVEN',
 'APERSONG',
 'AGEZONG',
 'AWAOREG',
 'ABRAND',
 'AZEILPL',
 'APLEZIER',
 'AFIETS',
 'AINBOED',
 'ABYSTAND']

In [10]:
def calc_iv(df, feature, target, pr=0):

    lst = []

    for i in range(df[feature].nunique()):
        val = list(df[feature].unique())[i]
        lst.append([feature, val, df[(df[feature] == val) & (df[target] == 0)].count()[feature], df[(df[feature] == val) & (df[target] == 1)].count()[feature]])
    
    data = pd.DataFrame(lst, columns=['Variable', 'Value', 'Good', 'Bad'])
    data = data[data['Bad'] > 0]

    data['Good Rate'] = data['Good'] / data['Good'].sum()
    data['Bad Rate'] = data['Bad'] / data['Bad'].sum()
    data['Distribution'] = (data['Good Rate'] - data['Bad Rate']) 
   
    data['WoE'] = np.log(data['Good Rate'] / data['Bad Rate'])
    data['IV'] = (data['WoE'] * (data['Distribution'])).sum()

    data = data.sort_values(by=['Variable', 'Value'], ascending=True)

    if pr == 1:
        print(data)

    return data['IV'].values[0]
    

In [11]:
z = []
for i in  range(0,len(x)):
    
     z.append(calc_iv(train, x[i],'CARAVAN'))

In [12]:
z

[0.3213751813950453,
 0.0007346871620147902,
 0.03422872286296251,
 0.017849675793993137,
 0.2612448541025786,
 0.03036948447022352,
 0.06936235652429497,
 0.03755662472722519,
 0.06577416141044545,
 0.12152575707158976,
 0.02641606980898759,
 0.10390314550369514,
 0.05947181733872561,
 0.0191623480438789,
 0.04043540780707397,
 0.12256159190535233,
 0.054130701983523336,
 0.16909317027548298,
 0.09271481240584496,
 0.012848473041037915,
 0.07277206198109536,
 0.06093336415162259,
 0.09560778230206628,
 0.06556822463591445,
 0.1107964290304866,
 0.04383235283384641,
 0.009885965390985307,
 0.09580118423956353,
 0.10843579791284452,
 0.14479265091201363,
 0.14314978410735255,
 0.11643792648433386,
 0.0040591263446180395,
 0.14398922708428055,
 0.07294839010796046,
 0.06918673273323918,
 0.16429838139119377,
 0.017902455898783223,
 0.12150149854264904,
 0.07503166630042474,
 0.006760411004750566,
 0.2193418579641816,
 0.20701652291829295,
 0.16428883255316318,
 0.004317665935919208,
 0.0

In [13]:
feature_index =[]

for i in range(len(z)):
    if z[i]> 0.1 and z[i]< 0.5:
        print(i)
        feature_index.append(i)

0
4
9
11
15
17
24
28
29
30
31
33
36
38
41
42
43
58
64
67
79


In [14]:
new = train.iloc[:,feature_index]
new.columns

Index(['ORIGIN', 'MGEMLEEF', 'MGODGE', 'MRELSA', 'MFWEKIND', 'MOPLMIDD',
       'MBERARBO', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT2', 'MZPART',
       'MINK3045', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAOREG', 'PBYSTAND',
       'AWALAND', 'AWAOREG'],
      dtype='object')

In [15]:
new = new.iloc[:,1:]
new.head()

MGEMLEEF  MGODGE  MRELSA  MFWEKIND  MOPLMIDD  MBERARBO  MSKC  MSKD  MHHUUR  \
1         2       4       2         5         5         4     5     0       2   
2         2       4       2         2         5         2     4     0       7   
3         3       4       2         4         4         2     4     0       5   
4         2       4       1         4         4         0     0     0       4   
5         1       5       6         2         5         2     4     2       9   

   MHKOOP  MAUT2  MZPART  MINK3045  MINK123M  MINKGEM  MKOOPKLA  PWAOREG  \
1       7      1       3         0         0        5         4        0   
2       2      0       0         5         0        3         4        0   
3       4      0       2         5         0        4         4        0   
4       5      2       4         0         0        6         3        0   
5       0      3       0         2         0        3         3        0   

   PBYSTAND  AWALAND  AWAOREG  
1         0        0        0  
2         0        0        0  
3         0        0        0  
4         0        0        0  
5         0        0        0

In [16]:
logit = LogisticRegression()

In [17]:
train_x,test_x,train_y,test_y = train_test_split(new,train.iloc[:,86],test_size = 0.3,random_state = 27)

In [18]:
logit.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
cross_val_score(estimator = logit,X=train_x,y=train_y,cv=3,n_jobs=-1)

array([0.94481236, 0.9455081 , 0.94546794])

In [20]:
c = logit.predict(test_x)
len(c)

1747

In [22]:
f1_score(c,test_y), accuracy_score(c,test_y),cohen_kappa_score(c,test_y)

C:\Users\Silla Naresh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


(0.0, 0.9284487693188322, 0.0)

In [23]:
confusion_matrix(c,test_y)

array([[1622,  125],
       [   0,    0]], dtype=int64)

In [24]:
test_new = test.iloc[:,feature_index]
test_new = test_new.iloc[:,1:]

In [25]:
c= logit.predict(test_new)

In [26]:
confusion_matrix(c,test.iloc[:,86])

array([[3761,  238],
       [   0,    0]], dtype=int64)

In [28]:
not_taken =train[train["CARAVAN"]==0]
taken = train[train["CARAVAN"]==1]

# upsample minority
upsampled = resample(taken,
                          replace=True, # sample with replacement
                          n_samples=len(not_taken), # match number in majority class
                          random_state=27) # reproducible results

In [29]:
not_taken_test =test[test["CARAVAN"]==0]
taken_test = test[test["CARAVAN"]==1]

# upsample minority

upsampled_test = resample(taken,
                          replace=True, # sample with replacement
                          n_samples=len(not_taken_test), # match number in majority class
                          random_state=27) # reproducible results

In [30]:
upsampled = pd.concat([not_taken, upsampled])
upsampled[upsampled["CARAVAN"]==0].shape,upsampled[upsampled["CARAVAN"]==1].shape

((5473, 87), (5473, 87))

In [31]:
upsampled_test = pd.concat([not_taken_test, upsampled_test])
upsampled_test[upsampled_test["CARAVAN"]==0].shape,upsampled_test[upsampled_test["CARAVAN"]==1].shape

((3761, 87), (3761, 87))

In [32]:
new = upsampled.iloc[:,feature_index]
new.shape
new.columns

Index(['ORIGIN', 'MGEMLEEF', 'MGODGE', 'MRELSA', 'MFWEKIND', 'MOPLMIDD',
       'MBERARBO', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT2', 'MZPART',
       'MINK3045', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAOREG', 'PBYSTAND',
       'AWALAND', 'AWAOREG'],
      dtype='object')

In [33]:
new = new.iloc[:,1:]
new.head()

MGEMLEEF  MGODGE  MRELSA  MFWEKIND  MOPLMIDD  MBERARBO  MSKC  MSKD  MHHUUR  \
1         2       4       2         5         5         4     5     0       2   
2         2       4       2         2         5         2     4     0       7   
3         3       4       2         4         4         2     4     0       5   
4         2       4       1         4         4         0     0     0       4   
5         1       5       6         2         5         2     4     2       9   

   MHKOOP  MAUT2  MZPART  MINK3045  MINK123M  MINKGEM  MKOOPKLA  PWAOREG  \
1       7      1       3         0         0        5         4        0   
2       2      0       0         5         0        3         4        0   
3       4      0       2         5         0        4         4        0   
4       5      2       4         0         0        6         3        0   
5       0      3       0         2         0        3         3        0   

   PBYSTAND  AWALAND  AWAOREG  
1         0        0        0  
2         0        0        0  
3         0        0        0  
4         0        0        0  
5         0        0        0

In [36]:
new.shape

(10946, 20)

In [37]:
train_x,test_x,train_y,test_y = train_test_split(new,upsampled.iloc[:,86],test_size = 0.3,random_state = 27)

In [38]:
logit.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [39]:
cross_val_score(estimator = logit,X=train_x,y=train_y,cv=3,n_jobs=-1)

array([0.61800391, 0.628426  , 0.60712887])

In [40]:
c = logit.predict(test_x)
len(c)


3284

In [41]:
f1_score(c,test_y), accuracy_score(c,test_y),cohen_kappa_score(c,test_y)

(0.6221956326652707, 0.6154080389768575, 0.23103568719145517)

In [42]:
confusion_matrix(c,test_y)

array([[ 981,  591],
       [ 672, 1040]], dtype=int64)

In [60]:
test_new = upsampled_test.iloc[:,feature_index]
test_new = test_new.iloc[:,1:]

In [44]:
c= logit.predict(test_new)

In [45]:
confusion_matrix(c,upsampled_test.iloc[:,86])

array([[2229, 1411],
       [1532, 2350]], dtype=int64)

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rf = RandomForestClassifier()

In [48]:
rf.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [49]:
cross_val_score(estimator = rf,X=train_x,y=train_y,cv=3,n_jobs=-1)

array([0.86966732, 0.87196554, 0.87230709])

In [51]:
c = rf.predict(test_x)

In [52]:
cohen_kappa_score(test_y,c),accuracy_score(test_y,c),f1_score(test_y,c)

(0.746921980528755, 0.8733252131546894, 0.8823529411764707)

In [53]:
confusion_matrix(c,test_y)

array([[1308,   71],
       [ 345, 1560]], dtype=int64)

In [61]:
c = rf.predict(test_new)

In [62]:
accuracy_score(c,upsampled_test.iloc[:,86])

0.8790215368253124

In [64]:
f1_score(c,upsampled_test.iloc[:,86])

0.8890243902439025